# Generated by Django 5.0.6 on 2024-06-18 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbotbackend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='status',
            field=models.CharField(default='Employee', max_length=50),
        ),
    ]
